Hand-tweaked the Pyrex-generated code!  Pyrex inserts its own prototype for pow(), instead of #including <math.h>.  This causes problems for the Linux BinBot when the code is compiled as C++:
_mpi.c:13: error: declaration of 'double pow(double, double)' throws different exceptions
/home/buildbot/opt/ibinbot/include/apbuild/glibc-2.2.1/bits/mathcalls.h:143: \
    error: than previous declaration 'double pow(double, double) throw ()'